defaults:
  - experiment: het_control_experiment
  - algorithm: iddpg
  - task: vmas/sampling
  - model: hetcontrolmlpempirical
  - model@critic_model: layers/mlp
  - _self_

seed: 0

# Whether to use the additional action loss to disincentive action outside the space
use_action_loss: True
action_loss_lr: 0.00003

experiment:
  max_n_frames: 5_000_000

hydra:
  searchpath:
   # Tells hydra to add the default benchmarl configuration to its path
    - pkg://benchmarl/conf